name: Build

on:
  # Trigger the workflow on pull request or push,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          MYDATOMIC_USER: ${{ secrets.MYDATOMIC_USER }}
          MYDATOMIC_PASSWORD: ${{ secrets.MYDATOMIC_PASSWORD }}
        run: ./build.sh build

      - name: Docker login
        run: docker login -u publisher -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Push
        run: ./build.sh push
